dsAudio:
    Type: sink
    Name: dsAudio_4_port

    # Profile for L1
    features:
        extendedEnumsSupported: false

    # dsAUDIOPORT_TYPE_ID_LR       = 0x00,  ///< RCA audio output
    # dsAUDIOPORT_TYPE_HDMI        = 0x01,  ///< HDMI audio output
    # dsAUDIOPORT_TYPE_SPDIF       = 0x02,  ///< SPDIF audio output
    # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,  ///< SPEAKER audio output
    # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,  ///< HDMI ARC/EARC audio output
    # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,  ///< Headphone jack
    # dsAUDIOPORT_TYPE_MAX         = 0x06   ///< Out of range
    PortTypes:
      - 0x02 #SPDIF
      - 0x03 #SPEAKER
      - 0x04 #HDMI_ARC
      - 0x05 #HEADPHONE

    # Number of supported ports
    Number_of_supported_ports: 4

    # dsAUDIOSUPPORT_NONE             = 0x0,     ///< None
    # dsAUDIOSUPPORT_ATMOS            = 0x01,    ///< Dolby Atmos
    # dsAUDIOSUPPORT_DD               = 0x02,    ///< Dolby Digitial
    # dsAUDIOSUPPORT_DDPLUS           = 0x04,    ///< Dolby Digital Plus
    # dsAUDIOSUPPORT_DAD              = 0x08,    ///< Digital Audio Delivery
    # dsAUDIOSUPPORT_DAPv2            = 0x10,    ///< Digital Audio Processing version 2
    # dsAUDIOSUPPORT_MS12             = 0x20,    ///< Multi Stream 12
    # dsAUDIOSUPPORT_MS12V2           = 0x40,    ///< Multi Stream Version 2
    # dsAUDIOSUPPORT_Invalid          = 0x80,    ///< Invalid
    Audio_Capabilities: 0x37  # dsAUDIOSUPPORT_ATMOS | dsAUDIOSUPPORT_DAPv2 | dsAUDIOSUPPORT_MS12 | dsAUDIOSUPPORT_DD | dsAUDIOSUPPORT_DDPLUS

    # Port details
    Ports:
        # Port Number to parse the port details
        1:
            # dsAUDIOPORT_TYPE_ID_LR       = 0x00,  ///< RCA audio output
            # dsAUDIOPORT_TYPE_HDMI        = 0x01,  ///< HDMI audio output
            # dsAUDIOPORT_TYPE_SPDIF       = 0x02,  ///< SPDIF audio output
            # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,  ///< SPEAKER audio output
            # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,  ///< HDMI ARC/EARC audio output
            # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,  ///< Headphone jack
            # dsAUDIOPORT_TYPE_MAX         = 0x06   ///< Out of range
            Typeid: 0x03  # SPEAKER
            # SPEAKER
            # HDMI_ARC
            # SPDIF
            # HEADPHONE
            Name: "SPEAKER"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            # Number of Supported Compressions
            number_of_supported_compressions: 4
            # dsAUDIO_CMP_NONE   = 0x00,  ///< No audio compression.
            # dsAUDIO_CMP_LIGHT  = 0x01,  ///< Light audio level compression.
            # dsAUDIO_CMP_MEDIUM = 0x02,  ///< Medium audio level compression.
            # dsAUDIO_CMP_HEAVY  = 0x03,  ///< Heavy audio level compression.
            # dsAUDIO_CMP_MAX    = 0x04   ///< Out of range
            compressions: [0x00, 0x01, 0x02, 0x03]  # NONE, LIGHT, MEDIUM, HEAVY
            # Number of supported Stereo modes
            number_of_supported_stereo_modes: 0
            # dsAUDIO_STEREO_UNKNOWN                   = 0x00, ///< Stereo mode none
            # dsAUDIO_STEREO_MONO                      = 0x01, ///< Mono mode
            # dsAUDIO_STEREO_STEREO                    = 0x02, ///< Normal stereo mode (L+R)
            # dsAUDIO_STEREO_SURROUND                  = 0x03, ///< Surround mode
            # dsAUDIO_STEREO_PASSTHRU                  = 0x04, ///< Passthrough mode
            # dsAUDIO_STEREO_DD                        = 0x05, ///< Dolby Digital
            # dsAUDIO_STEREO_DDPLUS                    = 0x06, ///< Dolby Digital Plus
            # dsAUDIO_STEREO_MAX                       = 0x07  ///< Out of range
            stereo_modes: []  # STEREO, SURROUND
            stereo_auto_mode: false
            # dsMS12SUPPORT_NONE                       = 0x0,   ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume                = 0x01,  //< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer        = 0x02,  ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer           = 0x04,  ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller             = 0x08,  ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer               = 0x10,  ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder            = 0x20,  ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode                    = 0x40,  ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer        = 0x80,  ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering                 = 0x100, ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer           = 0x200, ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig                   = 0x400, ///< MS12 LE config
            # dsMS12SUPPORT_Invalid                    = 0x800  ///< Invalid / Out of range
            MS12_Capabilities: 0xFFF  # DolbyVolume | IntelligentEqualizer | DialogueEnhancer
            # profile names from the "ms12_audio_profiles.ini" file.
            MS12_AudioProfiles:
              - "Off"
              - "User"
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 2
            # @a true if audio port supports Dolby MS12 Multistream Decoding or @a false otherwise
            IsMS12Decode: true
            # @a true if audio port supports Dolby MS11 Multistream Decoding or @a false otherwise
            IsMS11Decode: true
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00, ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_DDPLUSSTREAM               = 0x01, ///< can handle dd plus stream which is only way to pass ATMOS metadata
            # dsAUDIO_ATMOS_ATMOSMETADATA              = 0x02, ///< capable of parsing ATMOS metadata
            # dsAUDIO_ATMOS_MAX                        = 0x03  ///< Out of range
            ATMOS_Capabilities: 0x02  # ATMOSMETADATA
            dialog_enhancement_level:
                min: 0
                max: 12

        # Port Number to parse the port details
        2:
            # dsAUDIOPORT_TYPE_ID_LR       = 0x00,       ///< RCA audio output
            # dsAUDIOPORT_TYPE_HDMI        = 0x01,       ///< HDMI audio output
            # dsAUDIOPORT_TYPE_SPDIF       = 0x02,       ///< SPDIF audio output
            # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,       ///< SPEAKER audio output
            # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,       ///< HDMI ARC/EARC audio output
            # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,       ///< Headphone jack
            # dsAUDIOPORT_TYPE_MAX         = 0x06        ///< Out of range
            Typeid: 0x04  # HDMI_ARC
            # SPEAKER
            # HDMI_ARC
            # SPDIF
            # HEADPHONE
            Name: "HDMI_ARC"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            # number of supported compressions
            number_of_supported_compressions: 0
            # dsAUDIO_CMP_NONE   = 0x00, ///< No audio compression.
            # dsAUDIO_CMP_LIGHT  = 0x01, ///< Light audio level compression.
            # dsAUDIO_CMP_MEDIUM = 0x02, ///< Medium audio level compression.
            # dsAUDIO_CMP_HEAVY  = 0x03, ///< Heavy audio level compression.
            # dsAUDIO_CMP_MAX    = 0x04  ///< Out of range
            compressions:
            # Number of supported Stereo modes
            number_of_supported_stereo_modes: 4
            # dsAUDIO_STEREO_UNKNOWN                   = 0x00,  ///< Stereo mode none
            # dsAUDIO_STEREO_MONO                      = 0x01,  ///< Mono mode
            # dsAUDIO_STEREO_STEREO                    = 0x02,  ///< Normal stereo mode (L+R)
            # dsAUDIO_STEREO_SURROUND                  = 0x03,  ///< Surround mode
            # dsAUDIO_STEREO_PASSTHRU                  = 0x04,  ///< Passthrough mode
            # dsAUDIO_STEREO_DD                        = 0x05,  ///< Dolby Digital
            # dsAUDIO_STEREO_DDPLUS                    = 0x06,  ///< Dolby Digital Plus
            # dsAUDIO_STEREO_MAX                       = 0x07   ///< Out of range
            stereo_modes: [0x02, 0x04, 0x05, 0x06]  # STEREO, SURROUND, PASSTHRU
            stereo_auto_mode: true
            # dsMS12SUPPORT_NONE                       = 0x0,   ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume                = 0x01,  //< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer        = 0x02,  ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer           = 0x04,  ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller             = 0x08,  ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer               = 0x10,  ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder            = 0x20,  ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode                    = 0x40,  ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer        = 0x80,  ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering                 = 0x100, ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer           = 0x200, ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig                   = 0x400, ///< MS12 LE config
            # dsMS12SUPPORT_Invalid                    = 0x800  ///< Invalid / Out of range
            MS12_Capabilities: 0x00  # dsMS12SUPPORT_NONE
            MS12_AudioProfiles:
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 0
            # @a true if audio port supports Dolby MS12 Multistream Decoding or @a false otherwise
            IsMS12Decode: false
            # @a true if audio port supports Dolby MS11 Multistream Decoding or @a false otherwise
            IsMS11Decode: false
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00,  ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_DDPLUSSTREAM               = 0x01,  ///< can handle dd plus stream which is only way to pass ATMOS metadata
            # dsAUDIO_ATMOS_ATMOSMETADATA              = 0x02,  ///< capable of parsing ATMOS metadata
            # dsAUDIO_ATMOS_MAX                        = 0x03   ///< Out of range
            ATMOS_Capabilities: 0x00  # ATMOSMETADATA
            # dsAUDIOARCSUPPORT_NONE                   = 0x0,   ///< None
            # dsAUDIOARCSUPPORT_ARC                    = 0x01,  ///< Audio Return Channel
            # dsAUDIOARCSUPPORT_eARC                   = 0x02,  ///< Enhanced Audio Return Channel
            Arc_Types: 0x01 # dsAUDIOARCSUPPORT_ARC
            dialog_enhancement_level:
                min: 0
                max: 12

        # Port Number to parse the port details
        3:
            # dsAUDIOPORT_TYPE_ID_LR       = 0x00,      ///< RCA audio output
            # dsAUDIOPORT_TYPE_HDMI        = 0x01,      ///< HDMI audio output
            # dsAUDIOPORT_TYPE_SPDIF       = 0x02,      ///< SPDIF audio output
            # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,      ///< SPEAKER audio output
            # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,      ///< HDMI ARC/EARC audio output
            # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,      ///< Headphone jack
            # dsAUDIOPORT_TYPE_MAX         = 0x06       ///< Out of range
            Typeid: 0x02  # SPDIF
            # SPEAKER
            # HDMI_ARC
            # SPDIF
            # HEADPHONE
            Name: "SPDIF"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            #Number of supported compressions
            number_of_supported_compressions: 0
            #dsAUDIO_CMP_NONE     = 0x00,  ///< No audio compression.
            #dsAUDIO_CMP_LIGHT    = 0x01,  ///< Light audio level compression.
            #dsAUDIO_CMP_MEDIUM   = 0x02,  ///< Medium audio level compression.
            #dsAUDIO_CMP_HEAVY    = 0x03,  ///< Heavy audio level compression.
            #dsAUDIO_CMP_MAX      = 0x04   ///< Out of range
            compressions:
            #number of supported stereo modes
            number_of_supported_stereo_modes: 3
            #dsAUDIO_STEREO_UNKNOWN                   = 0x00,   ///< Stereo mode none
            #dsAUDIO_STEREO_MONO                      = 0x01,   ///< Mono mode
            #dsAUDIO_STEREO_STEREO                    = 0x02,   ///< Normal stereo mode (L+R)
            #dsAUDIO_STEREO_SURROUND                  = 0x03,   ///< Surround mode
            #dsAUDIO_STEREO_PASSTHRU                  = 0x04,   ///< Passthrough mode
            #dsAUDIO_STEREO_DD                        = 0x05,   ///< Dolby Digital
            #dsAUDIO_STEREO_DDPLUS                    = 0x06,   ///< Dolby Digital Plus
            #dsAUDIO_STEREO_MAX                       = 0x07    ///< Out of range
            stereo_modes: [0x02, 0x04, 0x05]  # STEREO, SURROUND, PASSTHRU
            stereo_auto_mode: true
            # dsMS12SUPPORT_NONE                       = 0x0,   ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume                = 0x01,  //< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer        = 0x02,  ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer           = 0x04,  ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller             = 0x08,  ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer               = 0x10,  ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder            = 0x20,  ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode                    = 0x40,  ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer        = 0x80,  ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering                 = 0x100, ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer           = 0x200, ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig                   = 0x400, ///< MS12 LE config
            # dsMS12SUPPORT_Invalid                    = 0x800  ///< Invalid / Out of range
            MS12_Capabilities: 0x00  # dsMS12SUPPORT_NONE
            MS12_AudioProfiles:
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 0
            # @a true if audio port supports Dolby MS12 Multistream Decoding or @a false otherwise
            IsMS12Decode: false
            # @a true if audio port supports Dolby MS11 Multistream Decoding or @a false otherwise
            IsMS11Decode: true
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00,  ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_DDPLUSSTREAM               = 0x01,  ///< can handle dd plus stream which is only way to pass ATMOS metadata
            # dsAUDIO_ATMOS_ATMOSMETADATA              = 0x02,  ///< capable of parsing ATMOS metadata
            # dsAUDIO_ATMOS_MAX                        = 0x03   ///< Out of range
            ATMOS_Capabilities: 0  # dsAUDIO_ATMOS_NOTSUPPORTED
            dialog_enhancement_level:
                min: 0
                max: 12

        # Port Number to parse the port details
        4:
            #dsAUDIOPORT_TYPE_ID_LR       = 0x00,      ///< RCA audio output
            #dsAUDIOPORT_TYPE_HDMI        = 0x01,      ///< HDMI audio output
            #dsAUDIOPORT_TYPE_SPDIF       = 0x02,      ///< SPDIF audio output
            #dsAUDIOPORT_TYPE_SPEAKER     = 0x03,      ///< SPEAKER audio output
            #dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,      ///< HDMI ARC/EARC audio output
            #dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,      ///< Headphone jack
            #dsAUDIOPORT_TYPE_MAX         = 0x06       ///< Out of range
            Typeid: 0x05  # HEADPHONE
            # SPEAKER
            # HDMI_ARC
            # SPDIF
            # HEADPHONE
            Name: "HEADPHONE"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            #Number of supported compressions
            number_of_supported_compressions: 0
            #dsAUDIO_CMP_NONE   = 0x00,  ///< No audio compression.
            #dsAUDIO_CMP_LIGHT  = 0x01,  ///< Light audio level compression.
            #dsAUDIO_CMP_MEDIUM = 0x02,  ///< Medium audio level compression.
            #dsAUDIO_CMP_HEAVY  = 0x03,  ///< Heavy audio level compression.
            #dsAUDIO_CMP_MAX    = 0x04   ///< Out of range
            compressions:
            #Number of Supported stereo modes
            number_of_supported_stereo_modes: 0
            #dsAUDIO_STEREO_UNKNOWN                   = 0x00,   ///< Stereo mode none
            #dsAUDIO_STEREO_MONO                      = 0x01,   ///< Mono mode
            #dsAUDIO_STEREO_STEREO                    = 0x02,   ///< Normal stereo mode (L+R)
            #dsAUDIO_STEREO_SURROUND                  = 0x03,   ///< Surround mode
            #dsAUDIO_STEREO_PASSTHRU                  = 0x04,   ///< Passthrough mode
            #dsAUDIO_STEREO_DD                        = 0x05,   ///< Dolby Digital
            #dsAUDIO_STEREO_DDPLUS                    = 0x06,   ///< Dolby Digital Plus
            #dsAUDIO_STEREO_MAX                       = 0x07    ///< Out of range
            stereo_modes:
            stereo_auto_mode: false
            # dsMS12SUPPORT_NONE                       = 0x0,   ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume                = 0x01,  //< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer        = 0x02,  ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer           = 0x04,  ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller             = 0x08,  ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer               = 0x10,  ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder            = 0x20,  ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode                    = 0x40,  ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer        = 0x80,  ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering                 = 0x100, ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer           = 0x200, ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig                   = 0x400, ///< MS12 LE config
            # dsMS12SUPPORT_Invalid                    = 0x800  ///< Invalid / Out of range
            MS12_Capabilities: 0x00  # dsMS12SUPPORT_NONE
            MS12_AudioProfiles:
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 0
            # @a true if audio port supports Dolby MS12 Multistream Decoding or @a false otherwise
            IsMS12Decode: false
            # @a true if audio port supports Dolby MS11 Multistream Decoding or @a false otherwise
            IsMS11Decode: false
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00,  ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_DDPLUSSTREAM               = 0x01,  ///< can handle dd plus stream which is only way to pass ATMOS metadata
            # dsAUDIO_ATMOS_ATMOSMETADATA              = 0x02,  ///< capable of parsing ATMOS metadata
            # dsAUDIO_ATMOS_MAX                        = 0x03   ///< Out of range
            ATMOS_Capabilities: 0  # dsAUDIO_ATMOS_NOTSUPPORTED
            dialog_enhancement_level:
                min: 0
                max: 12
