site_name: RDK HPK Documentation
site_url: https://github.com/rdkcentral/rdk-hpk-documentation
repo_url: https://github.com/rdkcentral/rdk-hpk-documentation
repo_name: rdkcentral/rdk-hpk-documentation
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Release: release.md
  - Components:
    - RMF Audio Capture:
      - API: external_content/rmf_audio_capture/docs/pages/rmf-audio-capture_halSpec.md
      - Changelog: external_content/rmf_audio_capture/CHANGELOG.md
      - Tests:
        - High Level: external_content/rmf_audio_capture_test/docs/pages/rmf-audio-capture_High-Level_TestSpec.md
        - L2 Low Level: external_content/rmf_audio_capture_test/docs/pages/rmf-audio-capture_L2-Low-Level_TestSpecification.md
        - L3 Low Level: external_content/rmf_audio_capture_test/docs/pages/rmf-audio-capture_L3_Low-Level_TestSpecification.md
        - L3 Test Procedure: external_content/rmf_audio_capture_test/docs/pages/rmf-audio-capture_L3_TestProcedure.md
        - Changelog: external_content/rmf_audio_capture_test/CHANGELOG.md
    - Power Manager:
      - API: external_content/power_manager/docs/pages/power-manager_halSpec.md
      - Changelog: external_content/power_manager/CHANGELOG.md
      - Tests:
        - High Level: external_content/power_manager_test/docs/pages/power-manager_High-Level_TestSpec.md
        - L2 Low Level: external_content/power_manager_test/docs/pages/power-manager_L2_Low-Level_TestSpec.md
        - Changelog: external_content/power_manager_test/CHANGELOG.md
    - Deep Sleep Manager:
      - API: external_content/deepsleep_manager/docs/pages/deepsleep-manager_halSpec.md
      - Changelog: external_content/deepsleep_manager/CHANGELOG.md
      - Tests:
        - High Level: external_content/deepsleep_manager_test/docs/pages/deep-sleep-manager_High-Level_TestSpec.md
        - L2 Low Level: external_content/deepsleep_manager_test/docs/pages/deep-sleep-manager_L2-Low-Level_TestSpec.md
        - L3 Low Level: external_content/deepsleep_manager_test/docs/pages/deep-sleep-manager_L3-Low-Level_TestSpec.md
        - L3 Test Procedure: external_content/deepsleep_manager_test/docs/pages/deep-sleep-manager_L3_TestProcedure.md
        - Changelog: external_content/deepsleep_manager_test/CHANGELOG.md
    - Device Settings:
      - DS Audio:
        - API: external_content/device_settings/docs/pages/ds-audio_halSpec.md
        - Tests:
            - High Level: external_content/device_settings_test/docs/pages/dsAudio/ds-audio_High-Level_TestSpecification.md
            - L2 Low Level: external_content/device_settings_test/docs/pages/dsAudio/ds-audio_L2_Low-Level_TestSpecification.md
            - L3 Low Level: external_content/device_settings_test/docs/pages/dsAudio/ds-audio_L3_Low-Level_TestSpecification.md
            - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsAudio/ds-audio_L3_TestProcedure.md
      - DS Composite In:
        - API: external_content/device_settings/docs/pages/ds-composite-in_halSpec.md
        - Tests:
            - High Level: external_content/device_settings_test/docs/pages/dsCompositeIn/ds-compositeIn-High-Level_TestSpec.md
            - L2 Low Level: external_content/device_settings_test/docs/pages/dsCompositeIn/ds-compositeIn-L2-Low-Level_TestSpec.md
            - L3 Low Level: external_content/device_settings_test/docs/pages/dsCompositeIn/ds-compositeIn-L3-Low-Level-TestSpec.md
            - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsCompositeIn/ds-compositeIn-L3-TestProcedure.md
      - DS Display:
        - API: external_content/device_settings/docs/pages/ds-display_halSpec.md
        - Tests:
          - L2 Low Level: external_content/device_settings_test/docs/pages/dsDisplay/ds-display-L2-Low-Level_TestSpec.md
          - High Level: external_content/device_settings_test/docs/pages/dsDisplay/ds-display-high-Level_TestSpec.md
          - L3 Low Level: external_content/device_settings_test/docs/pages/dsDisplay/ds-display_L3_Low-Level_TestSpecification.md
          - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsDisplay/ds-display_L3_TestProcedure.md
      - DS Front Panel Display:
        - API: external_content/device_settings/docs/pages/ds-front-panel-display_halSpec.md
        - Tests:
          - High Level: external_content/device_settings_test/docs/pages/dsFPD/ds-front-panel-display_High-Level_TestSpec.md
          - L2 Low Level: external_content/device_settings_test/docs/pages/dsFPD/ds-front-panel-display_L2_Low-Level_TestSpecification.md
          - L3 Low Level: external_content/device_settings_test/docs/pages/dsFPD/ds-front-panel-display_L3_Low-Level_TestSpecification.md
          - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsFPD/ds-front-panel-display_L3_TestProcedure.md
      - DS HDMI In:
        - API: external_content/device_settings/docs/pages/ds-hdmi-in_halSpec.md
        - Tests:
            - L3 Low: external_content/device_settings_test/docs/pages/dsHDMIIn/ds-Hdmi-In_L3_Low-Level_TestSpecification.md
            - High Level: external_content/device_settings_test/docs/pages/dsHDMIIn/ds-hdmi-in-High-Level_TestSpec.md
            - L2 Low Level: external_content/device_settings_test/docs/pages/dsHDMIIn/ds-hdmi-in-L2-Low-Level_TestSpec.md
            - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsHDMIIn/ds-hdmi-in_L3_Test-Procedure.md
      - DS Host:
        - API: external_content/device_settings/docs/pages/ds-host_halSpec.md
        - Tests:
            - High Level: external_content/device_settings_test/docs/pages/dsHost/ds-host_High-Level_TestSpecification.md
            - L2 Low Level: external_content/device_settings_test/docs/pages/dsHost/ds-host_L2_Low-Level_TestSpecification.md
            - L3 Low Level: external_content/device_settings_test/docs/pages/dsHost/ds-host_L3_Low-Level_TestSpec.md
            - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsHost/ds-host_L3_TestProcedure.md
      - DS Video Device:
        - API: external_content/device_settings/docs/pages/ds-video-device_halSpec.md
        - Tests:
            - High Level: external_content/device_settings_test/docs/pages/dsVideoDevice/ds-video-device_High-Level_TestSpec.md
            - L2 Low Level: external_content/device_settings_test/docs/pages/dsVideoDevice/ds-video-device_L2-Low-Level_TestSpec.md
            - L3 Low Level: external_content/device_settings_test/docs/pages/dsVideoDevice/ds-video-device_L3_Low-Level_TestSpecification.md
            - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsVideoDevice/ds-video-device_L3_TestProcedure.md
      - DS Video Port:
        - API: external_content/device_settings/docs/pages/ds-video-port_halSpec.md
        - Tests:
          - High Level: external_content/device_settings_test/docs/pages/dsVideoPort/ds-video-port_High-Level_TestSpec.md
          - L2 Low Level: external_content/device_settings_test/docs/pages/dsVideoPort/ds-video-port_L2_Low-Level_TestSpecification.md
          - L3 Low Level: external_content/device_settings_test/docs/pages/dsVideoPort/ds-video-port_L3_Low-Level_TestSpecification.md
          - L3 Test Procedure: external_content/device_settings_test/docs/pages/dsVideoPort/ds-video-port_L3_Test-Procedure.md
      - Changelog: external_content/device_settings/CHANGELOG.md
      - Tests Changelog: external_content/device_settings_test/CHANGELOG.md
    - HDMI CEC:
      - API: external_content/hdmi_cec/docs/pages/hdmi-cec_halSpec.md
      - Changelog: external_content/hdmi_cec/CHANGELOG.md
      - Tests:
        - Sink High Level: external_content/hdmi_cec_test/docs/pages/hdmi-cec-sink_High-Level_TestSpec.md
        - Sink L2 Low Level: external_content/hdmi_cec_test/docs/pages/hdmi-cec-sink_L2_Low-Level_TestSpec.md
        - Source High Level: external_content/hdmi_cec_test/docs/pages/hdmi-cec-source_High-Level_TestSpec.md
        - Source L2 Low Level: external_content/hdmi_cec_test/docs/pages/hdmi-cec-source_L2_Low-Level_TestSpec.md
        - L3 Low Level: external_content/hdmi_cec_test/docs/pages/hdmi-cec-L3-Low-Level_TestSpec.md
        - L3 Test Procedure: external_content/hdmi_cec_test/docs/pages/hdmi-cec-L3_TestProcedure.md
        - Virtual Component ControlPlane Commands: external_content/hdmi_cec_test/docs/pages/hdmi_cec_VirtualComponent_ControlPlaneCommands.md
        - Virtual Component Design: external_content/hdmi_cec_test/docs/pages/hdmi_cec_virtual_component_design.md
        - Changelog: external_content/hdmi_cec_test/CHANGELOG.md
    - TV Settings:
      - API: external_content/tvsettings/docs/pages/tv-settings_halSpec.md
      - Changelog: external_content/tvsettings/CHANGELOG.md
      - Tests:
        - High Level: external_content/tvsettings_test/docs/pages/tv-settings_High_Level_Test_Spec.md
        - L2 Low Level: external_content/tvsettings_test/docs/pages/tv-settings_L2_Low_Level_Test_Spec.md
        - L3 Low Level: external_content/tvsettings_test/docs/pages/tv-settings_L3_Low_Level_Test_Spec.md
        - L3 Test Procedure: external_content/tvsettings_test/docs/pages/tv-settings_L3_TestProcedure.md
        - Changelog: external_content/tvsettings_test/CHANGELOG.md
  - Miscellaneous:
    - Building Blocks:
      - UT-Core Test Framework:
        - UT-Core Overview: external_content/ut-core-wiki/Home.md
        - Level Actors: external_content/ut-core-wiki/FAQ:-UT-Core-Framework-Overview.md
      - Python RAFT:
        - Overview: external_content/python_raft_wiki/Home.md
    - Virtual Device:
      - What is the vDevice: external_content/ut-core-wiki/5.0:-Standards:-vDevice-Overview.md
      - Architecture Overview: external_content/ut-core-wiki/5.0.1:-Standards:-vDevice-Architecture-Overview.md
      - Key Concepts:
        - Controller: external_content/ut-core-wiki/5.1.0:-Standards:-vDevice-Controller.md
        - Control Plane: external_content/ut-core-wiki/5.1.1:-Standards:-vDevice-Control-Plane.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md




markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences  
  - toc:
      toc_depth: 4
  - pymdownx.emoji: # Enable Extended Emoji if required
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences: # Enable mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css  # Ensure this file exists
#  - stylesheets/version.css

extra:
  version:
    provider: mike # This enables mike integration for the version selector

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.4.1/mermaid.min.js
  - javascript/mermaid-init.js

theme:
  name: material
  features:
    - navigation.footer
    - navigation.sections     # Allows collapsible sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.print.stylesheet
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss
  repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
