
dsAudio:
    Type: source
    Name: dsAudio_1_port

    # Profile for L1
    features:
        extendedEnumsSupported: false

    # dsAUDIOPORT_TYPE_ID_LR       = 0x00,  ///< RCA audio output
    # dsAUDIOPORT_TYPE_HDMI        = 0x01,  ///< HDMI audio output
    # dsAUDIOPORT_TYPE_SPDIF       = 0x02,  ///< SPDIF audio output
    # dsAUDIOPORT_TYPE_SPEAKER     = 0x03,  ///< SPEAKER audio output
    # dsAUDIOPORT_TYPE_HDMI_ARC    = 0x04,  ///< HDMI ARC/EARC audio output
    # dsAUDIOPORT_TYPE_HEADPHONE   = 0x05,  ///< Headphone jack
    # dsAUDIOPORT_TYPE_MAX         = 0x06   ///< Out of range
    PortTypes:
      - 0x00 # ID_LR
      - 0x01 # HDMI
      - 0x02 # SPDIF

    # Number of supported ports
    Number_of_supported_ports: 1

    # dsAUDIOSUPPORT_NONE             = 0x0,     ///< None
    # dsAUDIOSUPPORT_ATMOS            = 0x01,    ///< Dolby Atmos
    # dsAUDIOSUPPORT_DD               = 0x02,    ///< Dolby Digitial
    # dsAUDIOSUPPORT_DDPLUS           = 0x04,    ///< Dolby Digital Plus
    # dsAUDIOSUPPORT_DAD              = 0x08,    ///< Digital Audio Delivery
    # dsAUDIOSUPPORT_DAPv2            = 0x10,    ///< Digital Audio Processing version 2
    # dsAUDIOSUPPORT_MS12             = 0x20,    ///< Multi Stream 12
    # dsAUDIOSUPPORT_MS12V2           = 0x40,    ///< Multi Stream Version 2
    # dsAUDIOSUPPORT_Invalid          = 0x80,    ///< Invalid
    Audio_Capabilities: 0x37  # dsAUDIOSUPPORT_ATMOS | dsAUDIOSUPPORT_DAPv2 | dsAUDIOSUPPORT_MS12 | dsAUDIOSUPPORT_DD | dsAUDIOSUPPORT_DDPLUS

    # Port details
    Ports:
        # Port Number to parse the port details
        1:
            # dsAUDIOPORT_TYPE_ID_LR       = 0x00,       ///< RCA audio output
            # dsAUDIOPORT_TYPE_HDMI        = 0x01,       ///< HDMI audio output
            # dsAUDIOPORT_TYPE_SPDIF       = 0x02,       ///< SPDIF audio output
            Typeid: 0x01  # HDMI
            Name: "HDMI"
            # An index value used to access a specific port within an array of ports with the same type.
            Index: 0
            # number of supported compressions
            number_of_supported_compressions: 4
            # dsAUDIO_CMP_NONE   = 0x00, ///< No audio compression.
            # dsAUDIO_CMP_LIGHT  = 0x01, ///< Light audio level compression.
            # dsAUDIO_CMP_MEDIUM = 0x02, ///< Medium audio level compression.
            # dsAUDIO_CMP_HEAVY  = 0x03, ///< Heavy audio level compression.
            compressions: [0x00, 0x01, 0x02, 0x03]  # NONE, LIGHT, MEDIUM, HEAVY
            # Number of supported Stereo modes
            number_of_supported_stereo_modes: 3
            # dsAUDIO_STEREO_UNKNOWN                   = 0x00,  ///< Stereo mode none
            # dsAUDIO_STEREO_MONO                      = 0x01,  ///< Mono mode
            # dsAUDIO_STEREO_STEREO                    = 0x02,  ///< Normal stereo mode (L+R)
            # dsAUDIO_STEREO_SURROUND                  = 0x03,  ///< Surround mode
            # dsAUDIO_STEREO_PASSTHRU                  = 0x04,  ///< Passthrough mode
            stereo_modes: [0x02, 0x03, 0x04]  # STEREO, SURROUND, PASSTHRU
            stereo_auto_mode: true
            # dsMS12SUPPORT_NONE                       = 0x0,   ///< MS12 Supported None
            # dsMS12SUPPORT_DolbyVolume                = 0x01,  //< MS12 supported Dolby Volume
            # dsMS12SUPPORT_InteligentEqualizer        = 0x02,  ///< MS12 supported Intelligent Equalizer
            # dsMS12SUPPORT_DialogueEnhancer           = 0x04,  ///< MS12 Dialogue Enhancer supported
            # dsMS12SUPPORT_Volumeleveller             = 0x08,  ///< MS12 Volume leveller
            # dsMS12SUPPORT_BassEnhancer               = 0x10,  ///< MS12 Bass Enhancer
            # dsMS12SUPPORT_SurroundDecoder            = 0x20,  ///< MS12 Surround Decoder
            # dsMS12SUPPORT_DRCMode                    = 0x40,  ///< MS12 DRC Mode
            # dsMS12SUPPORT_SurroundVirtualizer        = 0x80,  ///< MS12 Surround Virtualizer
            # dsMS12SUPPORT_MISteering                 = 0x100, ///< MS12 MI Steering
            # dsMS12SUPPORT_GraphicEqualizer           = 0x200, ///< MS12 Graphic equalizer
            # dsMS12SUPPORT_LEConfig                   = 0x400, ///< MS12 LE config
            # dsMS12SUPPORT_Invalid                    = 0x800  ///< Invalid / Out of range
            MS12_Capabilities: 0x4D  # DolbyVolume | IntelligentEqualizer | DialogueEnhancer
            MS12_AudioProfiles:
            # number of counts from the "ms12_audio_profiles.ini" file
            MS12_AudioProfileCount: 0
            IsMS12Decode: true
            IsMS11Decode: false
            # dsAUDIO_ATMOS_NOTSUPPORTED               = 0x00,  ///< ATMOS audio not supported
            # dsAUDIO_ATMOS_SUPPORTED                  = 0x01,  ///< ATMOS audio supported
            ATMOS_Capabilities: 0x01  # dsAUDIO_ATMOS_SUPPORTED
            dialog_enhancement_level:
                min: 0
                max: 12

